title: "Top Level Title"
schemaVersion: 1.0.0
version: "20190612"
locale: "en"
groupings:
  - title: "Hidden General Configuration"
    visible: true
    variables:
    - tenancy_ocid
    - compartment_ocid
    - region
    - server_version
    - syncgateway_version
    # QS specific platform vars
    #- ad_number
    - platform-images

  - title: "Couchbase Configuration"
    visible: true
    variables:
    #- ad_name
    - server_shape
    - server_count
    - syncgateway_shape
    - syncgateway_count
    - ssh_public_key
    - adminUsername
    - adminPassword

variables:
#  ad_name:
#    description: "Availability Domain where Couchbase instances are deployed."
#    type: oci:identity:availabilitydomain:name
#    dependsOn:
#      compartmentId: ${compartment_ocid}
#    required: true
#    title: "Availability Domain"

  server_shape:
    description: "Shape for Couchbase server instances."
    type: oci:core:instanceshape:name
    default: "VM.Standard2.2"
    title: "Compute Shape"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  server_count:
    description: "Number of Couchbase server instances."
    type: oci:core:instanceshape:name
    default: "VM.Standard2.2"
    title: "Compute Shape"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  syncgateway_shape:
    description: "Shape for Couchbase syncgateway instances."
    type: oci:core:instanceshape:name
    default: "VM.Standard2.2"
    title: "Compute Shape"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  syncgateway_count:
    description: "Number of Couchbase syncgateway instances."
    type: integer
    default: 0
    title: "Compute Shape"
    required: true

  ssh_public_key:
    description: "SSH public key for all instance."
    type: string
    required: true

#  disk_size_gb:
#    description: "Minimum size 50GB, <50GB volumes will not be created"
#    type: integer
#    required: true
#    default: 0
#    title: "Block Volume Size"

  adminUsername:
    description: "Default admin user."
    type: string
    default: "couchbase"
    required: true

  adminPassword:
    description: "Password for default user."
    type: password
    default: ""
    required: true

#  ad_number:
#    description: "Shadowed TF value to ignore"
#    type: integer
#    required: true
#    default: -1

  mp_listing_id:
    type: string
    required: true
    default: -1
